### ISSUE TITLE
Missing yaml files in configs

### ISSUE THREAD

**Issue by Big-Big-Dumpling** [lannguyen0910/food-detection-yolov5#15]
When I run the project through the python app.py, it noticed that the 'models'.yaml file is missed in 'utilities/configs' like, FileNotFoundError: [Errno 2] No such file or directory: 'utilities/configs/yolov5m.yaml' and it is also missed in './models/configs/detection' there even have no detection file under the configs path

**Comment by lannguyen0910** [comment]
Hi @Big-Big-Dumpling, i've fixed the following error. Thank you very much!
